sources: 
  arxiv: 
    enabled: true
    categories: ["cs.AI", "cs.CY"]
    # max_papers: 1000 
    max_papers: 5
    
  pmc:
    enabled: true
    # max_papers: 1000
    max_papers: 5
    sleep_records : 0.5
  
storage:
  raw_pdf_dir: data/raw/pdfs
  metadata_dir: data/raw/metadata